vsim -t 10ns -voptargs=+acc work.user_logic;
add wave sim:/user_logic/bus2ip_clk;
add wave sim:/user_logic/fwd_inv_we;
add wave sim:/user_logic/rfd;
add wave sim:/user_logic/start;
add wave sim:/user_logic/fwd_inv;
add wave sim:/user_logic/dv;
add wave sim:/user_logic/unload;
add wave sim:/user_logic/done;
add wave sim:/user_logic/busy;
add wave sim:/user_logic/edone;
add wave sim:/user_logic/xn_re;
add wave sim:/user_logic/xn_im;
add wave sim:/user_logic/xn_index;
add wave sim:/user_logic/xk_re;
add wave sim:/user_logic/xk_im;
add wave sim:/user_logic/xk_index;
#add wave sim:/user_logic/p1;
#add wave sim:/user_logic/p2;
add wave sim:/user_logic/p3;
add wave sim:/user_logic/x_out;
force -freeze sim:/user_logic/bus2ip_clk 1 0, 0 {10 ns} -r 20;
run 80000ns;